Fix example tpv rule
admin.config.admin_users is always set, and it is a list, so this fails
with
```
AttributeError: 'list' object has no attribute 'split'
```